### PR TITLE
what...

### PR DESCRIPTION
**Pull request by kingstefan26**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

- **What is the current behavior?** (You can also link to an open issue here)

- **What is the new behavior (if this is a feature change)?**

- **Other information**:

### CODE REVIEW

**Comment by kingstefan26** [comment]
why does it do that

**Comment by kingstefan26** [comment]
oh maybe cuz i didnt update my fork
lol

**Comment by Tricked-dev** [comment]
https://94e18baa.ascella.pages.dev/
image
doesnt seem to work

**Comment by kingstefan26** [comment]
mf is it the avif 💀💀💀??

**Comment by Tricked-dev** [comment]
probably lol

**Comment by kingstefan26** [comment]
ok eventually I'll get back to this

**Comment by Tricked-dev** [comment]
fair

**Comment by kingstefan26** [comment]
ok changed stuff
owo

**Comment by Tricked-dev** [comment]
uh

**Comment by kingstefan26** [comment]
ugh

**Pull request merged**
